language: node_js
node_js:
  - 8
before_script:
  - npm install @babel/core" --save-dev
  - npm install parcel-bundler --save-dev
script: parcel build src/index.html --out-dir .
deploy:
  fqdn: coreydmccarty.dev
  local-dir: _site
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master