language: node_js
node_js:
  - 8
before_script:
  - npm install @babel/core --save-dev
  - npm install parcel-bundler --save-dev
script: parcel build src/index.html
deploy:
  fqdn: corey.mccarty.dev
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
